// examples/lit/src/examples/virtual-list/components/ContactRow.ts
import { html, LitElement } from "lit";
import { property } from "lit/decorators.js";
import { __decorate } from "tslib";
import {
  type FieldApi,
  type FieldApiOptions,
  WatchController,
} from "@kin-form/lit";
import { email, required } from "@kin-form/validators";
import "./TextField.ts";

export type Contact = {
  name: string;
  email: string;
};

const nameOptions: FieldApiOptions<string, Contact> = {
  validators: [required("Required")],
};
const emailOptions: FieldApiOptions<string, Contact> = {
  validators: [required("Required"), email("Invalid email")],
};

/**
 * One virtualized row's fields.
 *
 * Row height is fixed (see `ContactList.ts`'s own doc comment for why): an
 * invalid+touched text field growing with an error message can visually
 * overlap the row below instead of pushing it down.
 */
export class ContactRow extends LitElement {
  // See `SubmitButton.ts`'s own doc comment for why these are `declare`d
  // rather than real class fields, with `index`'s default set in the
  // constructor instead of a field initializer.
  // deno-lint-ignore no-explicit-any
  declare api: FieldApi<Contact, any>;
  declare index: number;

  readonly #watch = new WatchController(this, () => this.api, (f) => f.dirty);

  constructor() {
    super();
    this.index = 0;
  }

  override createRenderRoot(): this {
    return this;
  }

  override render(): unknown {
    const dirty = this.#watch.value;
    const api = this.api;

    return html`
      <div class="flex items-start gap-3 border-b border-gray-100 px-3 py-2">
        <span
          class="w-10 shrink-0 pt-1.5 text-right text-xs tabular-nums text-gray-400">
          ${this.index + 1}
        </span>
        <div class="grid flex-1 grid-cols-2 gap-2">
          <virtual-list-text-field
            .api=${api.field("name", nameOptions)}
            placeholder="Name"
          ></virtual-list-text-field>
          <virtual-list-text-field
            .api=${api.field("email", emailOptions)}
            placeholder="Email"
          ></virtual-list-text-field>
        </div>
        <span
          title=${dirty ? "Edited, persists across scroll" : "Unedited"}
          class="mt-2 h-2 w-2 shrink-0 rounded-full ${dirty
            ? "bg-blue-500"
            : "bg-gray-200"}"
        ></span>
      </div>
    `;
  }
}

__decorate(
  [property({ attribute: false })],
  ContactRow.prototype,
  "api",
  void 0,
);
__decorate(
  [property({ type: Number })],
  ContactRow.prototype,
  "index",
  void 0,
);

customElements.define("contact-row", ContactRow);

declare global {
  interface HTMLElementTagNameMap {
    "contact-row": ContactRow;
  }
}

// examples/react/src/examples/virtual-list/components/ContactRow.tsx
import type { ReactNode } from "react";
import { type FieldApi, FieldApiOptions, Watch } from "@kin-form/react";
import { email, required } from "@kin-form/validators";
import { TextField } from "./TextField.tsx";

export type Contact = {
  name: string;
  email: string;
};

const nameOptions: FieldApiOptions<string, Contact> = {
  validators: [required("Required")],
};
const emailOptions: FieldApiOptions<string, Contact> = {
  validators: [required("Required"), email("Invalid email")],
};

export type ContactRowProps<TParentValue> = {
  api: FieldApi<Contact, TParentValue>;
  index: number;
};

/**
 * One virtualized row's fields.
 *
 * Row height isn't fixed: an invalid+touched `TextField` grows the row with
 * an error message, so the virtualizer measures each row's real height via
 * `measureElement` (see `App.tsx`) instead of trusting its `estimateSize`
 * guess.
 */
export function ContactRow<TParentValue>(
  { api, index }: ContactRowProps<TParentValue>,
): ReactNode {
  return (
    <div className="flex items-start gap-3 border-b border-gray-100 px-3 py-2">
      <span className="w-10 shrink-0 pt-1.5 text-right text-xs tabular-nums text-gray-400">
        {index + 1}
      </span>
      <div className="grid flex-1 grid-cols-2 gap-2">
        <TextField api={api.field("name", nameOptions)} placeholder="Name" />
        <TextField api={api.field("email", emailOptions)} placeholder="Email" />
      </div>
      <Watch api={api} select={(f) => f.dirty}>
        {(_api, dirty) => (
          <span
            title={dirty ? "Edited, persists across scroll" : "Unedited"}
            className={`mt-2 h-2 w-2 shrink-0 rounded-full ${
              dirty ? "bg-blue-500" : "bg-gray-200"
            }`}
          />
        )}
      </Watch>
    </div>
  );
}
